apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  creationTimestamp: '2020-04-28T20:08:01Z'
  generation: 2
  labels:
    app: es
  name: es
  namespace: default
  resourceVersion: '15279636'
  selfLink: /apis/apps/v1/namespaces/default/deployments/es
  uid: 164f0522-1850-48cb-a404-45362739069b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: es
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - env:
            - name: ELASTIC_CONTAINER
              value: 'true'
            - name: JAVA_HOME
              value: /opt/jdk-12
          image: 'registry-vpc.cn-beijing.aliyuncs.com/firsttest/elasticsearch:6.7.0'
          imagePullPolicy: IfNotPresent
          name: es
          ports:
            - containerPort: 9300
              protocol: TCP
            - containerPort: 9200
              protocol: TCP
          resources:
            requests:
              cpu: '1'
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-04-28T20:10:28Z'
      lastUpdateTime: '2020-04-28T20:10:28Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-04-28T20:08:01Z'
      lastUpdateTime: '2020-04-28T20:10:28Z'
      message: ReplicaSet "es-6f7ff9f4f6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
