apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '9'
  creationTimestamp: '2020-05-02T17:45:46Z'
  generation: 10
  labels:
    app: frontend
  name: frontend
  namespace: default
  resourceVersion: '69162178'
  selfLink: /apis/apps/v1/namespaces/default/deployments/frontend
  uid: ae2c26d6-7509-4406-abb8-fae01a289727
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: 'registry.cn-beijing.aliyuncs.com/firsttest/frontend:5'
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 80
              name: endpoint
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-05-02T17:45:46Z'
      lastUpdateTime: '2020-05-11T00:05:59Z'
      message: ReplicaSet "frontend-86bc7666d9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2020-05-11T10:12:47Z'
      lastUpdateTime: '2020-05-11T10:12:47Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
