apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '21'
  creationTimestamp: '2020-04-26T21:05:54Z'
  generation: 38
  labels:
    app: graph
  name: graph
  namespace: default
  resourceVersion: '18992651'
  selfLink: /apis/apps/v1/namespaces/default/deployments/graph
  uid: 457af319-e183-4548-86a4-048c8aae9ed3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: graph
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: graph
    spec:
      containers:
        - env:
            - name: LANG
              value: C.UTF-8
            - name: JAVA_HOME
              value: /usr/local/openjdk-8
            - name: JAVA_BASE_URL
              value: >-
                https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u252-b09/OpenJDK8U-jdk_
            - name: JAVA_OPTS
              value: '-Dconfig.resource=application-dev.conf'
            - name: CASSANDRA_PASSWORD
              value: nUqt36Z2sWW0
            - name: CASSANDRA_CONTACT_POINTS
              value: 192.168.0.145
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ELASTICSEARCH_HOST
              value: 192.168.0.156
          image: 'registry-vpc.cn-beijing.aliyuncs.com/firsttest/graph:0.2.14-SNAPSHOT'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: health/ready
              port: 8558
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: graph
          ports:
            - containerPort: 25520
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8558
              protocol: TCP
            - containerPort: 2551
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: health/alive
              port: 8558
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-04-28T20:24:13Z'
      lastUpdateTime: '2020-04-28T20:24:13Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-04-26T21:05:54Z'
      lastUpdateTime: '2020-04-29T16:54:17Z'
      message: ReplicaSet "graph-788547cc96" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 38
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
