apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
  creationTimestamp: '2020-04-29T04:03:13Z'
  generation: 5
  labels:
    app: saga
  name: saga
  namespace: default
  resourceVersion: '19207759'
  selfLink: /apis/apps/v1/namespaces/default/deployments/saga
  uid: 1280b674-0508-4c34-93ed-4b29c3e5c265
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: saga
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: saga
    spec:
      containers:
        - env:
            - name: LANG
              value: C.UTF-8
            - name: JAVA_HOME
              value: /usr/local/openjdk-8
            - name: JAVA_BASE_URL
              value: >-
                https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u252-b09/OpenJDK8U-jdk_
            - name: SEED_NODE
              value: 192.168.0.171
            - name: JAVA_OPTS
              value: '-Dconfig.resource=saga-application-dev.conf'
            - name: CASSANDRA_PASSWORD
              value: nUqt36Z2sWW0
            - name: CASSANDRA_CONTACT_POINTS
              value: 192.168.0.145
            - name: ELASTICSEARCH_HOST
              value: 192.168.0.156
          image: 'registry-vpc.cn-beijing.aliyuncs.com/firsttest/saga:0.2.2-SNAPSHOT'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: health/alive
              port: 8558
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: saga
          ports:
            - containerPort: 25520
              protocol: TCP
            - containerPort: 8558
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: health/ready
              port: 8558
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: Default
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2020-04-29T04:28:19Z'
      lastUpdateTime: '2020-04-29T04:28:19Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-04-29T04:03:13Z'
      lastUpdateTime: '2020-04-29T17:58:59Z'
      message: ReplicaSet "saga-8dc5f4fbd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
